parameters:
#    redbear_resume.example.class: Redbear\ResumeBundle\Example

services:
#    redbear_resume.example:
#        class: %redbear_resume.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
